defmodule Aoc.Day07Test do
  use ExUnit.Case

  import Elixir.Aoc.Day07

  def test_input() do
    """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """
  end

  test "part1" do
    input = test_input()
    result = part1(input)

    assert result == 21
  end

  test "part2" do
    input = test_input()
    result = part2(input)

    assert result == 40
  end
end
